split: skip zero len writes
Jigsaw-Code/Intra pull request #519
Opened 2024-06-26 10:06 UTC by ignoramous

I'm not sure why (as zero len writes are apparently no-op in Golang) but the Quad9 resolver (DNSCrypt over TCP) doesn't work without this check.

2024-06-28 22:38 UTC, jyyi1 requested changes

2024-06-28 22:38 UTC, jyyi1 commented on Android/app/src/go/intra/split/retrier.go
> +			return n, nil
```suggestion
			if buf := b[n:]; len(buf) > 0 {
				m, e := r.conn.Write(buf)
				n += m
				err = e
			}
			return n, err
```

2024-06-28 22:38 UTC, jyyi1 commented on Android/app/src/go/intra/split/retrier.go
> +			leftover := b[n:]
```suggestion
```

2024-06-28 22:38 UTC, jyyi1 commented on Android/app/src/go/intra/split/retrier.go
> +
Please also add a comment here to explain the reason we are skipping 0-len buffers.

2024-06-28 23:44 UTC, ignoramous commented on Android/app/src/go/intra/split/retrier.go
> +			return n, nil
Nice. Thanks.

2024-07-01 22:44 UTC, jyyi1 approved these changes

2024-07-01 22:45 UTC, merged

2024-07-25 23:09 UTC, Kjs7945 commented
> I'm not sure why (as zero len writes are apparently no-op in Golang) but the Quad9 resolver (DNSCrypt over TCP) doesn't work without this check.

2025-03-22 01:51 UTC, dekwan44 approved these changes