retrier: confirm splitHello to io.Writer.Write
Jigsaw-Code/Intra pull request #520
Opened 2024-08-16 21:24 UTC by ignoramous

The our code is written, writing to (via `io.Copy`) `retrier` (`DuplexConn`) results in panic when total written bytes from TLS fragmentation exceeds the length of the input bytes; expected since this behaviour violates the [`io.Writer.Write`](https://pkg.go.dev/io#Writer) contract:

> It returns the number of bytes written from p (0 <= n <= len(p)) and any error encountered that caused the write to stop early. Write must return a non-nil error if it returns n < len(p).

2024-08-16 23:03 UTC, jyyi1 requested changes
Returning `len(hello)` seems simple, but calculating actual written bytes is trickier, especially if a `Write` fails. We may or may not subtract the header length from `n`, depending on the bytes that has been written.

Since this is a private function, and we are not using the returned bytes, I recommend leaving it unchanged.

Please do not use this function elsewhere. For reusable TLS fragmentation, use the [Outline SDK](https://pkg.go.dev/github.com/Jigsaw-Code/outline-sdk@v0.0.16/transport/tlsfrag).

2024-08-16 23:49 UTC, ignoramous commented
> Since this is a private function, and we are not using the returned bytes

`splitter` (which impls `io.Writer` via `DuplexConn`) does use `n` returned from `splitHello`.

https://github.com/Jigsaw-Code/Intra/blob/27637e0ed497dbd1e862750b14f9a5c0be368f15/Android/app/src/go/intra/split/direct_split.go#L57

> Please do not use this function elsewhere. For reusable TLS fragmentation, use the Outline SDK. (We plan to refactor our code using the Outline SDK in the future as well)

Ah, thanks.

> We may or may not subtract the header length from n, depending on the bytes that has been written ... I recommend leaving it unchanged

I didn't quite catch this. 

You reckon we change `splitter.Write` to confirm to `io.Writer` or close this PR?

2024-08-17 00:22 UTC, jyyi1 commented
Thanks @ignoramous for your response. I suggest closing this PR if its purpose is solely for third-party use (Outline SDK is a more suitable API with proper handling of written bytes), since we'll be refactoring this logic anyway.

However, if you're aware of any Intra use cases that might be affected, we may need to fix it.

2024-08-17 00:39 UTC, ignoramous commented
> we'll be refactoring this logic anyway.

Gotcha.

> However, if you're aware of any Intra use cases that might be affected, we may need to fix it.

Well, only `splitter` (aka `direct_split`) but it isn't used by Intra anymore, even though (as it was brought to my attention, `direct_split` works better in face of ["residual censorship"](https://datatracker.ietf.org/doc/html/rfc9505#name-residual-censorship)).

(thanks for your input. closing...)

2024-08-17 00:39 UTC, closed without merging